// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbjmoengsybadtltctrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiam1vZW5nc3liYWR0bHRjdHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTU1MjIsImV4cCI6MjA2NzEzMTUyMn0.M2mz0KSEBvfFgoLmFm4eeYVtNrTs-4DOQ-U7BQh3imA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});